name: Android generate baseline profile

on:
  push:
    branches:
      - dev

jobs:
  baseline:
    name: generate-baselineprofile
    runs-on: macOS-latest

    env:
      EMULATOR_API_LEVEL: '30'
      EMULATOR_AVD_TARGET: 'aosp_atd'
      EMULATOR_AVD_ARCH: 'x86'

    steps:
      - name: Checkout to git repository
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Check LFS files
        uses: actionsdesk/lfs-warning@v3.3

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '22'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build benchmark
        id: gradle
        run: ./gradlew :apps:wallet:instance:main:generateReleaseBaselineProfile

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.EMULATOR_API_LEVEL }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.EMULATOR_API_LEVEL }}
          target: ${{ env.EMULATOR_AVD_TARGET }}
          arch: ${{ env.EMULATOR_AVD_ARCH }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."